CREATE TABLE IF NOT EXISTS Category (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR( 100 ) NOT NULL UNIQUE,
    description VARCHAR( 255 ) NOT NULL,
    lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Waste (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR( 100 ) NOT NULL,
    description VARCHAR( 255 ) NOT NULL,
    categoryId INT NOT NULL,
    lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ( categoryId ) REFERENCES category( id ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Disposal (
    id INT AUTO_INCREMENT PRIMARY KEY,
    wasteId INT NOT NULL,
    method VARCHAR( 100 ) NOT NULL,
    instructions VARCHAR( 255 ) NOT NULL,
    location VARCHAR( 100 ),
    lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ( wasteId ) REFERENCES waste( id ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS RecyclingTips (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    tip VARCHAR(244) NOT NULL,
    categoryId INT,
    wasteId INT,
    lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (categoryId) REFERENCES Category(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (wasteId) REFERENCES Waste(id) ON DELETE CASCADE ON UPDATE CASCADE
);
